Feature/name api keys
shlinkio/shlink pull request #1045
Opened 2021-03-06 17:51 UTC by KetchupBomb

Addresses #1044.

```
 $ ./indocker bin/cli api-key:list
+-----+------+------------+-----------------+-------+
| Key | Name | Is enabled | Expiration date | Roles |
+-----+------+------------+-----------------+-------+

$ ./indocker bin/cli api-key:generate > /dev/null
$ ./indocker bin/cli api-key:list
+--------------------------------------+------+------------+-----------------+-------+
| Key                                  | Name | Is enabled | Expiration date | Roles |
+--------------------------------------+------+------------+-----------------+-------+
| 66b8fe6f-f3e0-4c2f-80c6-27b851d96dba | -    | +++        | -               | Admin |
+--------------------------------------+------+------------+-----------------+-------+

$ ./indocker bin/cli api-key:generate --name Alice > /dev/null
$ ./indocker bin/cli api-key:list
+--------------------------------------+-------+------------+-----------------+-------+
| Key                                  | Name  | Is enabled | Expiration date | Roles |
+--------------------------------------+-------+------------+-----------------+-------+
| 66b8fe6f-f3e0-4c2f-80c6-27b851d96dba | -     | +++        | -               | Admin |
| d56bafdc-7350-4b5e-a547-771b34483fcb | Alice | +++        | -               | Admin |
+--------------------------------------+-------+------------+-----------------+-------+

# Note: In order to pass 'Alice and Bob' as a single string via indocker, the wrapped quotations are required.
$ ./indocker bin/cli api-key:generate -m "'Alice and Bob'" > /dev/null
$ ./indocker bin/cli api-key:list
+--------------------------------------+---------------+------------+-----------------+-------+
| Key                                  | Name          | Is enabled | Expiration date | Roles |
+--------------------------------------+---------------+------------+-----------------+-------+
| 66b8fe6f-f3e0-4c2f-80c6-27b851d96dba | -             | +++        | -               | Admin |
| d56bafdc-7350-4b5e-a547-771b34483fcb | Alice         | +++        | -               | Admin |
| 288414c1-02b1-4bdf-a718-edc305dacbd6 | Alice and Bob | +++        | -               | Admin |
+--------------------------------------+---------------+------------+-----------------+-------+
```

---

Known issues:

**1. `GenerateKeyCommandTest.php` has two errors:**

```
$ ./indocker composer test:unit
...
Generate Key Command (ShlinkioTest\Shlink\CLI\Command\Api\GenerateKeyCommand)
 ✘ No expiration date is defined if not provided
   ┐
   ├ TypeError: Double\ApiKeyServiceInterface\P5::create(): Return value must be of type Shlinkio\Shlink\Rest\Entity\ApiKey, null returned
   │
   ╵ /home/shlink/module/CLI/src/Command/Api/GenerateKeyCommand.php:96
   ╵ /home/shlink/vendor/symfony/console/Command/Command.php:256
   ╵ /home/shlink/vendor/symfony/console/Tester/CommandTester.php:76
   ╵ /home/shlink/module/CLI/test/Command/Api/GenerateKeyCommandTest.php:45
   ┴

 ✘ Expiration date is defined if provided
   ┐
   ├ TypeError: Double\ApiKeyServiceInterface\P5::create(): Return value must be of type Shlinkio\Shlink\Rest\Entity\ApiKey, null returned
   │
   ╵ /home/shlink/module/CLI/src/Command/Api/GenerateKeyCommand.php:96
   ╵ /home/shlink/vendor/symfony/console/Command/Command.php:256
   ╵ /home/shlink/vendor/symfony/console/Tester/CommandTester.php:76
   ╵ /home/shlink/module/CLI/test/Command/Api/GenerateKeyCommandTest.php:58
   ┴

ERRORS!
Tests: 616, Assertions: 3174, Errors: 2.
...
```

**2. API tests claim `shlink_test` doesn't exist, but it does. Probably my invocation of the tool is wrong:**

```
$ ./indocker composer test:api 
> bin/test/run-api-tests.sh
Server is not running
Starting server...
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

The command "'vendor/bin/doctrine' 'orm:schema-tool:drop' '--force' '--no-interaction' '-q'" failed.

Exit Code: 1(General error)

Working directory: /home/shlink

Output:
================

Error Output:
================

In AbstractPostgreSQLDriver.php line 88:
                                                                               
  An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  database "shli  
  nk_test" does not exist                                                      
                                                                               

In Exception.php line 18:
                                                                     
  SQLSTATE[08006] [7] FATAL:  database "shlink_test" does not exist  
                                                                     

In PDOConnection.php line 38:
                                                                     
  SQLSTATE[08006] [7] FATAL:  database "shlink_test" does not exist  
                                                                     

orm:schema-tool:drop [--dump-sql] [-f|--force] [--full-database]

Stopping server ...
Server stopped
Script bin/test/run-api-tests.sh handling the test:api event returned with error code 1

$ mysql -uroot -proot -h 127.0.0.1 -P 3307 -e 'SHOW DATABASES;'
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| shlink             |
| shlink_test        |
| sys                |
+--------------------+
```

---

Thanks for your eyes, @acelaya.

2021-03-06 17:52 UTC, KetchupBomb commented on module/CLI/src/Command/Api/GenerateKeyCommand.php
> +
- [ ] Is the position of this help text ok?
- [ ] Is `-m` as the short code for `--name` acceptable?

2021-03-06 18:00 UTC, KetchupBomb commented on module/Rest/test/Service/ApiKeyServiceTest.php
> +        yield 'null name' => [null, null, []];
Data providers `no expiration date` and `null name` are essentially duplicates of each other. I think this should remain as such, since each test is mean to test a different functionality, which _happen_ to overlap at the current point in time.

Just pointing this out for others to comment if this should change.

2021-03-06 18:48 UTC, acelaya requested changes
Looks quite good in general, thanks a lot.

I answered to your comments and added a few more.

2021-03-06 18:48 UTC, acelaya commented on module/CLI/src/Command/Api/ListKeysCommand.php
> +            $rowData[] = $apiKey->getName() ?? '-';
Yep, sounds good

2021-03-06 18:48 UTC, acelaya commented on module/CLI/test/Command/Api/ListKeysCommandTest.php
> +            | ghi |               | -               | Admin |
It could definitely be validated and filtered, ensuring emptysh values to be set as null, but honestly, being just a value for the human with no side effects, I don't think it's critical if any value is allowed.

We can keep it simple and allow `''`, `' '` and such.

2021-03-06 18:48 UTC, acelaya commented on module/Rest/config/entities-mappings/Shlinkio.Shlink.Rest.Entity.ApiKey.php
> +
I've never cared too much about the order of columns in the database. This position is perfect 🙂

2021-03-06 18:48 UTC, acelaya commented on module/Rest/src/Entity/ApiKey.php
> +    public function __construct(?Chronos $expirationDate = null, ?string $name = null)
Yep, the constructor is the place to add it, or on a named constructor if anything. No setter.

2021-03-06 18:48 UTC, acelaya commented on module/Rest/src/Entity/ApiKey.php
> +    public static function withName(string $key, ?string $name): self
This method might be missleading, as it's called `withName`, but you are actually not forcing the name to be provided. At the same time you are requesting the key.

I this case, if you added this method to be able to set both values for the tests, I would instead extend the `withKey` constructor, and add the name as a third optional param (I created the `withKey` named constructor just for the tests).

Otherwise, if the `withName` method is still useful for other context, I would keep it with this signature:

```php
public static function withName(string $name): self
{
    // ...
}
```

2021-03-06 18:48 UTC, acelaya commented on module/Rest/src/Entity/ApiKey.php
> +    public function getName(): ?string
I'm gradually moving away from getters in the form of `getFoo()`, and instead using the `foo()` approach, so I would suggest to name this method `name()`.

I know it's not consistent with some other getters, but I plan to refactor that soon.

2021-03-06 18:48 UTC, acelaya commented on module/Rest/test/Service/ApiKeyServiceTest.php
> +        yield 'null name' => [null, null, []];
I don't think it makes sense to test the same twice just for the sake of semantics. Instead, change the name to `'no expiration date or name'`.

2021-03-06 18:48 UTC, acelaya commented on module/Rest/test/Service/ApiKeyServiceTest.php
> +        yield 'multiple names' => [null, 'Alice and Bob', []];
Instead of `multiple names`, I would call this `multi-word name` or `composed name`, as the name is still just one.

2021-03-06 18:48 UTC, acelaya commented on module/CLI/src/Command/Api/GenerateKeyCommand.php
> +
Yes to both.

2021-03-06 18:48 UTC, acelaya commented on module/CLI/test/Command/Api/ListKeysCommandTest.php
> +            +-----+------+------------+-----------------+-------+
Because if you provide `--enabled-only`, the output only includes enabled API keys, therefore, it's redundant to show if the keys are enabled, as they implicitly are.

When I implemented this, I remember thinking if I should still keep the column for consistency and to simplify the logic, but I finally decided to remove it 🤷🏼‍♂️

2021-03-06 18:50 UTC, acelaya commented
BTW, you need to add a database migration too. The entity definition is for people installing Shlink from scratch, but people updating from older versions already have a database that needs to be updated.

Migrations are in the `data/migrations` folder. The `Version20210202181026` one is a good example as it's also creating new columns.

2021-03-06 18:54 UTC, acelaya commented
> 1. GenerateKeyCommandTest.php has two errors

For this issue, check how the `ApiKeyService::create` is mocked. Most probably it is mocked for when it's called with the old signature. Since you added a new argument in between, it's not capturing that invokation, which is the one mocked to return an `ApiKey` instance, and instead it returns `void`, which is prophecy's default behavior.

Look for something like `apiKeyService->create(...)->willReturn(...)`. The `...` encapsuled in `create(...)` needs to match the way it's actually invoked inside `GenerateKeyCommand`.

2021-03-06 18:55 UTC, acelaya commented
> 2. API tests claim shlink_test doesn't exist, but it does. Probably my invocation of the tool is wrong

Have you set-up your local dev environment? The only thing that comes to my mind is that you are maybe missing some step. Take a look at this and check if you are missing something: https://github.com/shlinkio/shlink/blob/develop/CONTRIBUTING.md

2021-03-06 19:00 UTC, acelaya commented on module/Rest/src/Service/ApiKeyService.php
> +        RoleDefinition ...$roleDefinitions,
I think all those errors thrown in tests and static analysis under PHP 7.4 are because of this comma after `$roleDefinitions`.

That is valid in PHP 8, but not in PHP 7.4

`Error: ParseError (syntax error, unexpected ')', expecting variable (T_VARIABLE))`.

It happens both in ApiKeyService and ApiKeyServiceInterface.

2021-03-06 23:46 UTC, KetchupBomb commented on module/CLI/test/Command/Api/ListKeysCommandTest.php
> +            +-----+------+------------+-----------------+-------+
Oh, I see, that's handled by the function arguments:

```
public function returnsExpectedOutput(..., bool $enabledOnly, ...)
```

I missed that and was blindly copy-and-pasting existing Data Providers, which blindly copied the `true` argument. Derp.

2021-03-06 23:50 UTC, KetchupBomb commented on module/Rest/src/Entity/ApiKey.php
> +    public static function withName(string $key, ?string $name): self
I noticed the `with*()` functions were solely used in tests, which is why I added `withName()`.

I actually originally extended `withKey()` to have an additional parameter for `$name`, but decided to go with `withName()` to make it clear that this was for testing the `$name` parameter handling.

Now that I know you agree to extend `withKey()`, I'll switch back to that.

2021-03-07 01:53 UTC, KetchupBomb reviewed
* Fixed all Unit tests. 🎉
* Addressed comments.
* Added migration file.

Still working on:
* `test:api` continues to complain about a missing `shlink_test` database, but it's present. 🤷‍♂️

2021-03-07 01:53 UTC, KetchupBomb commented on module/CLI/test/Command/Api/GenerateKeyCommandTest.php
> +            Argument::type('string')    // Name
Just because I'd like to know why things don't work... @acelaya, I tried using the `::class` property of PHP's String class, but no dice:

```
Argument::type(string::class)
// Also tried
Argument::type(String::class)
```

Neither worked, so went with what it is now. Any ideas as to why? I don't remember if PHP's String class is `string` or `String`, but neither worked. 😞

2021-03-07 01:53 UTC, KetchupBomb commented on module/Rest/config/entities-mappings/Shlinkio.Shlink.Rest.Entity.ApiKey.php
> +
The consequence of _not_ putting this column at the end of the table is mentioned in the migration file included.

2021-03-07 01:53 UTC, KetchupBomb commented on data/migrations/Version20210306165711.php
> +        $this->addSql('ALTER TABLE api_keys ADD COLUMN `name` VARCHAR(255) AFTER `key`');
@acelaya, FYI.

Does this change your opinion? Should the column go at the end of the table?

2021-03-07 07:00 UTC, acelaya requested changes
Looks really good. Just added one comment for the migration.

Once that is changed, we are ready to merge.

2021-03-07 07:00 UTC, acelaya commented on data/migrations/Version20210306165711.php
> +        $this->addSql('ALTER TABLE api_keys ADD COLUMN `name` VARCHAR(255) AFTER `key`');
Unfortunately Shlink cannot have raw SQL on it's migrations, as it sports 5 different database engines.

Because of that, you have to use the `Schema` object as you did on the `down` method.

Don't worry about the position. Just let the migration add the column at the end. It's fine.

2021-03-07 07:02 UTC, acelaya commented on module/CLI/test/Command/Api/GenerateKeyCommandTest.php
> +            Argument::type('string')    // Name
There's no String class in PHP, string is a scalar type, like boolean or int.

For all those, you have to pass the type as string (`Argument::type('string')`, `Argument::type('int')`, etc).

So what you ended up doing is correct.

2021-03-07 08:22 UTC, acelaya commented
> test:api continues to complain about a missing shlink_test database, but it's present. man_shrugging

I have just realized what's probably the issue. I changed not long ago to use Postgres for the API tests, so the testing database needs to be created in the postgres engine container, not in the MySQL one.

I have just updated the `CONTRIBUTING.md` file.

2021-03-07 22:14 UTC, acelaya commented
Thanks a lot fior the contribution. Not many people takes the time to work on new features.

I really appreciate the effort and time you spent here 🙂

2021-03-07 22:14 UTC, merged

2021-03-08 02:21 UTC, KetchupBomb commented
Thank you for your help and quick feedback, @acelaya. Your documentation is really good, too.

Until next time.