Feature/show API key info in short-url CLI
shlinkio/shlink pull request #1064
Opened 2021-04-05 04:46 UTC by KetchupBomb

Addresses #1059.

Adds two new CLI flags:

* `--show-api-key`
* `--show-api-key-name`

---

Data from development:

```shell
$ ./indocker bin/cli short-url:list --all --show-api-key --show-api-key-name
+------------+-------+-----------------------------+-----------------------------------------------------------------+---------------------------+--------------+--------------------------------------+---------------+
| Short Code | Title | Short URL                   | Long URL                                                        | Date created              | Visits count | API Key                              | API Key Name  |
+------------+-------+-----------------------------+-----------------------------------------------------------------+---------------------------+--------------+--------------------------------------+---------------+
| RGhvf      |       | http://localhost:8080/RGhvf | https://github.com/shlinkio/shlink/issues/1059                  | 2021-04-02T04:47:07+00:00 | 0            | 3e17f144-e349-4f12-96a2-6f058abdff25 |               |
| cLciN      |       | http://localhost:8080/cLciN | https://github.com/shlinkio/shlink/blob/develop/CONTRIBUTING.md | 2021-04-02T04:51:44+00:00 | 0            | 3d8a7c8d-e2bc-47ce-b66f-af0b84f92587 | Alice and Bob |
| 0IcFP      |       | http://localhost:8080/0IcFP | https://github.com/KetchupBomb/shlink                           | 2021-04-02T04:52:17+00:00 | 0            | db67d697-c85a-4ded-8170-67b1e7b51c61 |               |
| vaYMW      |       | http://localhost:8080/vaYMW | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:26+00:00 | 0            | e1a0b5a3-abe0-4940-971c-3e66c7408464 |               |
| dccBh      |       | http://localhost:8080/dccBh | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:27+00:00 | 0            | 55340df1-fe96-4182-a40c-1bead370d285 | Foobar        |
| 6Q2lr      |       | http://localhost:8080/6Q2lr | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:28+00:00 | 0            | 60156032-76f5-4e31-be06-baf15ea3adae |               |
| BFrcq      |       | http://localhost:8080/BFrcq | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:28+00:00 | 0            |                                      |               |
| N2qTV      |       | http://localhost:8080/N2qTV | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:28+00:00 | 0            | 55340df1-fe96-4182-a40c-1bead370d285 | Foobar        |
| t1kwF      |       | http://localhost:8080/t1kwF | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:29+00:00 | 0            | 55340df1-fe96-4182-a40c-1bead370d285 | Foobar        |
| kZXKC      |       | http://localhost:8080/kZXKC | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:29+00:00 | 0            | 55340df1-fe96-4182-a40c-1bead370d285 | Foobar        |
| 80eEF      |       | http://localhost:8080/80eEF | https://github.com/KetchupBomb/shlink/tree/main                 | 2021-04-02T04:52:30+00:00 | 0            |                                      |               |
+------------+-------+-----------------------------+-----------------------------------------------------------------+---------------------------+--------------+--------------------------------------+---------------+

                                                                                                                        
 [OK] Short URLs properly listed                                                                                        
                                                                                                                        
```

Currently, if there is no API key or API key name associated, it's a blank entry. This matches existing logic within `short-url:list` (like `Title`), but doesn't match other commands like `api-key:list`, where empty entries are represented with `-`. I'm leaving this discrepancy unaddressed in this diff.

2021-04-05 04:57 UTC, KetchupBomb reviewed
FYI, I didn't provide additional tests, since I think the values provided demonstrate the possible outcomes from various database states. If additional tests are needed, I could use some pointers.

2021-04-05 04:57 UTC, KetchupBomb commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
>      ];
I refactored this bit into a `private` function further below -- it seemed better than keep track of one-off flags like `--tags`.

2021-04-05 04:57 UTC, KetchupBomb commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
> +                ],
Here, for at least `short-url:list`, any additional flags which reference other tables can be placed into this block to better manage column name and `ShortUrlDataTransformer` fields.

2021-04-05 04:57 UTC, KetchupBomb commented on module/Core/src/ShortUrl/Transformer/ShortUrlDataTransformer.php
> +                ? (string) $shortUrl->getAuthorApiKey()
Do you prefer this `(string)` casting, or should I explicitly call `->toString()`?

2021-04-05 04:57 UTC, KetchupBomb commented on module/Core/src/ShortUrl/Transformer/ShortUrlDataTransformer.php
> +                : null,
I've seen somewhere in your docs that you're planning on deprecating PHP 7. [PHP 8's nullsafe operator](https://www.php.net/releases/8.0/en.php#nullsafe-operator) will be welcome!

```
'authorApiKeyName' => $shortUrl->getAuthorApiKey()?->name(),
```

2021-04-05 04:57 UTC, KetchupBomb commented on module/Rest/test-api/Action/ListShortUrlsTest.php
> +        'authorApiKeyName' => null,
I couldn't surface why some of these `const`s needed `null` vs `'author_api_key'` as a value. I used the existing unit tests to provide the proper value. 😅

2021-04-05 05:07 UTC, KetchupBomb commented
btw, PHP Stan _was_ working, but it appears to be busted after I rebased on top of the latest commits from your `develop` branch:

```
 $ ./indocker composer stan
> phpstan analyse module/*/src/ module/*/config config docker/config data/migrations --level=6
Note: Using configuration file /home/shlink/phpstan.neon.
 278/278 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------------------------------- 
  Line   config/autoload/mercure.global.php                                  
 ------ -------------------------------------------------------------------- 
  24     Class Symfony\Component\Mercure\Hub not found.                      
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  31     Class Symfony\Component\Mercure\Hub not found.                      
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  31     Class Symfony\Component\Mercure\HubInterface not found.             
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------- 
  Line   module/Core/config/event_dispatcher.config.php                      
 ------ -------------------------------------------------------------------- 
  60     Class Symfony\Component\Mercure\Hub not found.                      
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   module/Core/src/EventDispatcher/NotifyVisitToMercure.php                                                                                                             
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  20     Property Shlinkio\Shlink\Core\EventDispatcher\NotifyVisitToMercure::$hub has unknown class Symfony\Component\Mercure\HubInterface as its type.                       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                                                   
  26     Parameter $hub of method Shlinkio\Shlink\Core\EventDispatcher\NotifyVisitToMercure::__construct() has invalid typehint type Symfony\Component\Mercure\HubInterface.  
  51     Call to method publish() on an unknown class Symfony\Component\Mercure\HubInterface.                                                                                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                                                   
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 -- -------------------------------------------------------------------------------------------------------------------------------------- 
     Error                                                                                                                                 
 -- -------------------------------------------------------------------------------------------------------------------------------------- 
     Ignored error pattern #setOrderBy\(\) expects array<int, string\>, array<string, string\> given# was not matched in reported errors.  
 -- -------------------------------------------------------------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 8 errors                                                                                                 
                                                                                                                        

Script phpstan analyse module/*/src/ module/*/config config docker/config data/migrations --level=6 handling the stan event returned with error code 1
```

But the integration tests on Github are complaining about a rogue parenthesis... I am able to execute code in my Docker environment, so I'm not sure if the integration tests are a red herring.

2021-04-05 07:53 UTC, acelaya requested changes
Looks good on the CLI part, and I like the approach you took by using the new flags. I just left few minor comments there.

However, in the way you did this, it impacts the REST API, while it shouldn't. No changes should happen in the REST API, and in no circumstances anything related with API keys should be leaked through REST endpoints, as it would introduce security issues.

Let's keep the tranformer as it was, to remove all those side effects it comes from, and instead let's call the new getter just in the console command.

As per the errors being thrown in the static analysis step, it's because you introduced some changes that do not work on PHP 7.4, while they do on PHP 8, like the trailing comma in the last argument of multi-line function definitions.

And the errors you get while running it locally, I would say you should probably rebase `develop` branch and then run `composer update`. I think that should fix it.

2021-04-05 07:53 UTC, acelaya commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
> +        bool $all,
This trailing comma does not work in PHP 7.4
```suggestion
        bool $all
```

2021-04-05 07:53 UTC, acelaya commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
> +        'Visits count' => 'visitsCount',
With this new approach, I would rename this constant from `COLUMNS_TO_SHOW` to `HUMAN_FRIENDLY_COLUMN_NAMES_MAP`.

2021-04-05 07:53 UTC, acelaya commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
> +        $showParams = $this->columnsToShow($input);
`$showParams` is a bit confusing, as it makes you think it's a boolean flag. I had to scroll up and down to understand what it was.

Maybe a better name would be `$columnsMap` or something in those lines.

2021-04-05 07:53 UTC, acelaya commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
> +        array $showParams,
Same as mentioned above. This should be named something like `$columnsMap`.

2021-04-05 07:53 UTC, acelaya commented on module/CLI/src/Command/ShortUrl/ListShortUrlsCommand.php
> +                ],
I like this approach, and also allowing the API key and name to be optionally displayed through flags.

2021-04-05 07:53 UTC, acelaya commented on module/Core/src/Entity/ShortUrl.php
> +    public function getAuthorApiKey(): ?ApiKey
I'm moving away from the `get` prefix in getters. Could you call this method just `authorApiKey`?

2021-04-05 07:53 UTC, acelaya commented on module/Core/src/ShortUrl/Transformer/ShortUrlDataTransformer.php
> +                ? (string) $shortUrl->getAuthorApiKey()
Oh, no, this should not be here. This will expose the API key through the API endpoints, which is a huge security problem.

The API keys should be only accesible through the CLI. I would suggest keeping the transformer as it is and calling this getter from the console command only.

2021-04-05 07:53 UTC, acelaya commented on module/Rest/test-api/Action/ListShortUrlsTest.php
> +        'authorApiKeyName' => null,
The REST API should not be changed as part of this PR.

2021-04-05 16:34 UTC, KetchupBomb commented on module/Core/src/ShortUrl/Transformer/ShortUrlDataTransformer.php
> +                ? (string) $shortUrl->getAuthorApiKey()
I understand the security implications. I didn't know this was causing the key to be exposed to the API. Whoops! 😰

At first, I didn't see that `LitShortUrlsCommand` actually had access to a `ShortUrl` object -- I misread it, thinking it was a requirement to go through `ShortUrlDataTransformer`. I'll incorporate changes and update.

Thank you again for quick, clear, and actionable feedback!

2021-04-10 07:21 UTC, KetchupBomb commented
Ugh. I'm terrible with Git. Is there any way I can recover this PR, for at least history sake?

If not, I have incorporated changes to [my `develop` branch](https://github.com/KetchupBomb/shlink/tree/develop), and all test appear to be passing. I could just PR again...

<details>
  <summary><code>./indocker compose ci:parallel</code></summary>

```
[30;43mRunning tasks in parallel:[39;49m
[30;43mcs[39;49m
[30;43mstan[39;49m
[30;43mtest:unit:ci[39;49m
[30;43mtest:db:sqlite:ci[39;49m
[30;43mtest:db:mysql[39;49m
[30;43mtest:db:maria[39;49m
[30;43mtest:db:postgres[39;49m
[30;43mtest:db:ms[39;49m

[32mFinished task stan[39m
> phpstan analyse module/*/src/ module/*/config config docker/config data/migrations --level=6
Note: Using configuration file /home/shlink/phpstan.neon.
   0/280 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
[2K 280/280 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%



 [OK] No errors                                                                 



[32mFinished task test:db:maria[39m
> DB_DRIVER=maria composer test:db:sqlite
> APP_ENV=test php vendor/bin/phpunit --order-by=random --colors=always --testdox -c phpunit-db.xml
Script APP_ENV=test php vendor/bin/phpunit --order-by=random --colors=always --testdox -c phpunit-db.xml handling the test:db:sqlite event returned with error code 1
Script DB_DRIVER=maria composer test:db:sqlite handling the test:db:maria event returned with error code 1

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Error in bootstrap script: Symfony\Component\Process\Exception\ProcessFailedException:
The command "'vendor/bin/doctrine' 'orm:schema-tool:drop' '--force' '--no-interaction' '-q'" failed.

Exit Code: 1(General error)

Working directory: /home/shlink

Output:
================


Error Output:
================

In AbstractMySQLDriver.php line 112:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 's  
  hlink_test'                                                                  
                                                                               

In Exception.php line 18:
                                                         
  SQLSTATE[HY000] [1049] Unknown database 'shlink_test'  
                                                         

In PDOConnection.php line 39:
                                                         
  SQLSTATE[HY000] [1049] Unknown database 'shlink_test'  
                                                         

orm:schema-tool:drop [--dump-sql] [-f|--force] [--full-database]




[32mFinished task test:db:ms[39m
> DB_DRIVER=mssql composer test:db:sqlite
> APP_ENV=test php vendor/bin/phpunit --order-by=random --colors=always --testdox -c phpunit-db.xml
Script APP_ENV=test php vendor/bin/phpunit --order-by=random --colors=always --testdox -c phpunit-db.xml handling the test:db:sqlite event returned with error code 1
Script DB_DRIVER=mssql composer test:db:sqlite handling the test:db:ms event returned with error code 1

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Error in bootstrap script: Symfony\Component\Process\Exception\ProcessFailedException:
The command "'vendor/bin/doctrine' 'orm:schema-tool:drop' '--force' '--no-interaction' '-q'" failed.

Exit Code: 1(General error)

Working directory: /home/shlink

Output:
================


Error Output:
================

In DBALException.php line 185:
                                                                               
  An exception occurred while executing 'SELECT name FROM sys.schemas WHERE n  
  ame NOT IN('guest', 'INFORMATION_SCHEMA', 'sys')':                           
                                                                               
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cann  
  ot open database "shlink_test" requested by the login. The login failed.     
                                                                               

In Exception.php line 18:
                                                                               
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cann  
  ot open database "shlink_test" requested by the login. The login failed.     
                                                                               

In PDOConnection.php line 39:
                                                                               
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cann  
  ot open database "shlink_test" requested by the login. The login failed.     
                                                                               

orm:schema-tool:drop [--dump-sql] [-f|--force] [--full-database]




[32mFinished task test:db:sqlite:ci[39m
> APP_ENV=test php vendor/bin/phpunit --order-by=random --colors=always --testdox -c phpunit-db.xml '--coverage-php' 'build/coverage-db.cov' '--coverage-xml=build/coverage-db/coverage-xml' '--log-junit=build/coverage-db/junit.xml'

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Random Seed:   1618038959

 [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [36m◒[0m running tests[1K[27D [36m◐[0m running tests[1K[27D[4mDomain Repository (ShlinkioTest\Shlink\Core\Domain\Repository\DomainRepository)[0m
 [32m✔[0m Find domains returns expected result
 [36m◓[0m running tests[1K[27D [32m✔[0m Find domains returns just those matching provided api key

[4mShort Url Repository (ShlinkioTest\Shlink\Core\Repository\ShortUrlRepository)[0m
 [32m✔[0m Find one with domain fallback returns proper data
 [32m✔[0m Count list returns proper number of results
 [32m✔[0m Find list properly filters result
 [32m✔[0m Find list properly maps field names to column names when ordering
 [32m✔[0m Short code is in use looks for short url in proper set of tables
 [32m✔[0m Find one looks for short url in proper set of tables
 [32m✔[0m Find one matching returns null for non existing short urls
 [32m✔[0m Find one matching applies proper conditions
 [32m✔[0m Find one matching returns oldest one when there are multiple matches
 [32m✔[0m Find one matching applies provided api key conditions
 [32m✔[0m Imported short urls are searched as expected
 [36m◓[0m running tests[1K[27D
[4mTag Repository (ShlinkioTest\Shlink\Core\Repository\TagRepository)[0m
 [32m✔[0m Delete by name does nothing when empty list is provided
 [36m◓[0m running tests[1K[27D [32m✔[0m All tags which match name are deleted
 [36m◓[0m running tests[1K[27D [36m◑[0m running tests[1K[27D [32m✔[0m Proper tags info is returned
 [32m✔[0m Tag exists returns expected result based on api key

[4mVisit Repository (ShlinkioTest\Shlink\Core\Repository\VisitRepository)[0m
 [32m✔[0m Find visits returns proper visits[2m with data set [22m[36m0[0m
 [32m✔[0m Find visits returns proper visits[2m with data set [22m[36m1[0m
 [32m✔[0m Find visits returns proper visits[2m with data set [22m[36m2[0m
 [32m✔[0m Find visits returns proper visits[2m with data set [22m[36m3[0m
 [32m✔[ [...]

2021-04-10 08:00 UTC, acelaya commented
You can push to your branch. It will get the PR updated.

2021-04-10 17:01 UTC, KetchupBomb commented
Sorry, I don't follow.

I _did_ push to my branch -- you can even see it reported [in my fork](https://github.com/KetchupBomb/shlink/tree/develop):

> This branch is 1 commit ahead, 4 commits behind shlinkio:develop.

(The 4 commits behind is from the past ~12 hours, additional code must've landed.)

2021-04-10 20:42 UTC, acelaya commented
Sorry, my mistake. I misunderstood what you meant when you said "recover this PR".

I have reopened it, so it should be ok now. I'll give it another reviewal tomorrow morning.

Thanks!

2021-04-11 09:38 UTC, acelaya commented
Hey @KetchupBomb, I have pushed some changes to your branch and I think it is now ready to merge.

The changes I have done are:

* Fixed the coding styles.
* Changed the approach to resolve a short URL property after piping it through the transformer. The way you did it it was calling `->transform` for the same ShortUrl for every single property, which was suboptimal.
* Added some tests covering all the new optional flags. The test was a bit weak already.

I like some of the ideas you have introduced in this PR, so I really appreciate your contribution 🙂 

Thanks!

2021-04-11 09:42 UTC, acelaya approved these changes

2021-04-11 09:42 UTC, merged

2021-04-11 09:46 UTC, acelaya commented
BTW, you are now the TOP 3 contributor of the project 🙂 

![image](https://user-images.githubusercontent.com/2719332/114299450-94be6680-9abb-11eb-8cd2-f82faabb193a.png)

2021-04-11 21:09 UTC, KetchupBomb commented
Thanks for addressing my PR, @acelaya. I didn't put in any tests since I wanted to check if the non-use of modifying the Transformer class was what you were thinking. Thanks for filling in the test cases for me, along with all the other nits addressed. 😃 

The amount of effort you put in to support Shlink is amazing, let alone the collaboration you provide for contributors.