Change the Docker user to non-root
shlinkio/shlink pull request #1108
Opened 2021-06-13 22:56 UTC by kanadaj

There is absolutely no reason to make the user run as root at runtime, and poses a security liability. This PR changes the only relevant folders to be writable by the user ID 1001, then changes the default Docker user to 1001.

Ownership is set for individual folders rather than recursively, so the _migrations_ and _infra_ folders should effectively act as read-only.

2021-06-14 16:04 UTC, acelaya commented
I will have to test this one carefully, as it's one of those things where it's so easy to introduce a regression, but if nothing breaks, in not opposed to it.

2021-07-13 20:00 UTC, acelaya requested changes

2021-07-13 20:00 UTC, acelaya commented on Dockerfile
> +RUN chown 1001 /etc/shlink/data/log
Why not `RUN chown -R 1001 /etc/shlink/data`?

2021-07-14 10:31 UTC, kanadaj commented on Dockerfile
> +RUN chown 1001 /etc/shlink/data/log
Because the folder also contains the migrations subfolder, and those should stay as read only

2021-07-15 17:56 UTC, acelaya commented on Dockerfile
> +RUN chown 1001 /etc/shlink/data/log
Yep. Makes sense.

2021-07-15 18:19 UTC, acelaya approved these changes

2021-07-15 18:19 UTC, merged

2021-07-15 18:19 UTC, acelaya commented
Thanks for the contribution 🙂

2021-08-01 08:03 UTC, acelaya commented
I had to finally disable this, as it breaked a cronjob that is configured for the root user when the `ENABLE_PERIODIC_VISIT_LOCATE` env var is provided.

I haven't seen an easy way to keep both, so I have moved back to use root in the docker image.

If you know a solution for this, I will be more than happy to enable it back.